name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 23 * * *'

jobs:
  system:
    name: Link to system zlib
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - uses: mattnite/setup-gyro@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install zlib1g-dev

      - if: ${{ matrix.os == 'macos-latest' }}
        run: brew install zlib

      - run: gyro build -Dlink=system run

  local:
    name: Link to locally built zlib
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        link: [static, shared]
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - uses: mattnite/setup-gyro@v1
      - uses: actions/checkout@v2
      - run: gyro build -Dlink=${{ matrix.link }} run
  local-windows:
    name: Link to locally built zlib on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        link: [static]
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - uses: mattnite/setup-gyro@v1
      - uses: actions/checkout@v2
      - run: gyro build -Dlink=${{ matrix.link }} -Dtarget=x86_64-windows-gnu run
